<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="4" total="12" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite B" duration-ms="19" started-at="2014-07-11T10:29:51Z" finished-at="2014-07-11T10:29:51Z">
    <groups>
    </groups>
    <test name="Test B1" duration-ms="1" started-at="2014-07-11T10:29:51Z" finished-at="2014-07-11T10:29:51Z">
      <class name="testSuiteB.TestB1">
        <test-method status="PASS" signature="testB1_1()[pri:0, instance:testSuiteB.TestB1@3020ad]" name="testB1_1" duration-ms="1" started-at="2014-07-11T15:59:51Z" finished-at="2014-07-11T15:59:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB1_1 -->
        <test-method status="FAIL" signature="testB1_3()[pri:0, instance:testSuiteB.TestB1@3020ad]" name="testB1_3" duration-ms="0" started-at="2014-07-11T15:59:51Z" finished-at="2014-07-11T15:59:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[failed test case ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: failed test case 
	at org.testng.Assert.fail(Assert.java:94)
	at testSuiteB.TestB1.testB1_3(TestB1.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB1_3 -->
        <test-method status="PASS" signature="testB1_2()[pri:0, instance:testSuiteB.TestB1@3020ad]" name="testB1_2" duration-ms="0" started-at="2014-07-11T15:59:51Z" finished-at="2014-07-11T15:59:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB1_2 -->
      </class> <!-- testSuiteB.TestB1 -->
    </test> <!-- Test B1 -->
    <test name="Test B2" duration-ms="1" started-at="2014-07-11T10:29:51Z" finished-at="2014-07-11T10:29:51Z">
      <class name="testSuiteB.TestB2">
        <test-method status="PASS" signature="testB2_1()[pri:0, instance:testSuiteB.TestB2@16dadf9]" name="testB2_1" duration-ms="0" started-at="2014-07-11T15:59:51Z" finished-at="2014-07-11T15:59:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB2_1 -->
        <test-method status="FAIL" signature="testB2_2()[pri:0, instance:testSuiteB.TestB2@16dadf9]" name="testB2_2" duration-ms="0" started-at="2014-07-11T15:59:51Z" finished-at="2014-07-11T15:59:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[failed test case ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: failed test case 
	at org.testng.Assert.fail(Assert.java:94)
	at testSuiteB.TestB2.testB2_2(TestB2.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB2_2 -->
        <test-method status="PASS" signature="testB2_3()[pri:0, instance:testSuiteB.TestB2@16dadf9]" name="testB2_3" duration-ms="0" started-at="2014-07-11T15:59:51Z" finished-at="2014-07-11T15:59:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB2_3 -->
      </class> <!-- testSuiteB.TestB2 -->
    </test> <!-- Test B2 -->
  </suite> <!-- Suite B -->
  <suite name="Suite A" duration-ms="61" started-at="2014-07-11T10:29:51Z" finished-at="2014-07-11T10:29:51Z">
    <groups>
    </groups>
    <test name="Test A1" duration-ms="14" started-at="2014-07-11T10:29:51Z" finished-at="2014-07-11T10:29:51Z">
      <class name="testSuiteA.TestA1">
        <test-method status="SKIP" signature="testA1_1()[pri:0, instance:testSuiteA.TestA1@b6e39f]" name="testA1_1" duration-ms="4" started-at="2014-07-11T15:59:51Z" finished-at="2014-07-11T15:59:51Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test
	at testSuiteA.TestA1.testA1_1(TestA1.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA1_1 -->
        <test-method status="FAIL" signature="testA1_3()[pri:0, instance:testSuiteA.TestA1@b6e39f]" name="testA1_3" duration-ms="2" started-at="2014-07-11T15:59:51Z" finished-at="2014-07-11T15:59:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[failed test case ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: failed test case 
	at org.testng.Assert.fail(Assert.java:94)
	at testSuiteA.TestA1.testA1_3(TestA1.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA1_3 -->
        <test-method status="PASS" signature="testA1_2()[pri:0, instance:testSuiteA.TestA1@b6e39f]" name="testA1_2" duration-ms="0" started-at="2014-07-11T15:59:51Z" finished-at="2014-07-11T15:59:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA1_2 -->
      </class> <!-- testSuiteA.TestA1 -->
    </test> <!-- Test A1 -->
    <test name="Test A2" duration-ms="0" started-at="2014-07-11T10:29:51Z" finished-at="2014-07-11T10:29:51Z">
      <class name="testSuiteA.TestA2">
        <test-method status="PASS" signature="testA2_1()[pri:0, instance:testSuiteA.TestA2@2c1e6b]" name="testA2_1" duration-ms="0" started-at="2014-07-11T15:59:51Z" finished-at="2014-07-11T15:59:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA2_1 -->
        <test-method status="PASS" signature="testA2_3()[pri:0, instance:testSuiteA.TestA2@2c1e6b]" name="testA2_3" duration-ms="0" started-at="2014-07-11T15:59:51Z" finished-at="2014-07-11T15:59:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA2_3 -->
        <test-method status="FAIL" signature="testA2_2()[pri:0, instance:testSuiteA.TestA2@2c1e6b]" name="testA2_2" duration-ms="0" started-at="2014-07-11T15:59:51Z" finished-at="2014-07-11T15:59:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[failed test case ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: failed test case 
	at org.testng.Assert.fail(Assert.java:94)
	at testSuiteA.TestA2.testA2_2(TestA2.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA2_2 -->
      </class> <!-- testSuiteA.TestA2 -->
    </test> <!-- Test A2 -->
  </suite> <!-- Suite A -->
  <suite name="My suite" duration-ms="0" started-at="2014-07-11T10:29:52Z" finished-at="2014-07-11T10:29:52Z">
    <groups>
    </groups>
  </suite> <!-- My suite -->
</testng-results>
